### ISSUE TITLE
Add support for Python 3.11

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#1897]
### Description of issue

Python 3.11 released on 2022-10-24 and nimi-python does not yet officially support it.
In order to claim support, we need nimibot to run all the automated tests on all the supported platforms.

**Comment by marcoskirsch** [comment]
I installed 

```
C:\Users\mkirsch>python --version
Python 3.11.2
```

and module `nidcpower`. Running a basic example:

```
import nidcpower

with nidcpower.Session(resource_name="Dev1") as session:
    print (session.serial_number)
```

outputs the following error:

```
C:\Users\mkirsch>python nidcpower.py
Traceback (most recent call last):
  File "C:\Users\mkirsch\nidcpower.py", line 1, in <module>
    import nidcpower
  File "C:\Users\mkirsch\nidcpower.py", line 3, in <module>
    with nidcpower.Session(resource_name="Dev1") as session:
         ^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'nidcpower' has no attribute 'Session' (most likely due to a circular import)
```

I don't know yet if this is a problem on my end or a problem with `nidcpower` on Python 3.11.2.
