### ISSUE TITLE
Input lists don't work

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#505]
Some functions (notably in the NI-FGEN API) require client to pass in an array / list. Our generator doesn't handle it correctly. We just turn around and hand it off to the Library class. 

See this error I got while writing an NI-DCPower example (attribute_ids is a Python list):

```
Z:\>python src\nidcpower\examples\nidcpower_advanced_sequence.py
Traceback (most recent call last):
  File "src\nidcpower\examples\nidcpower_advanced_sequence.py", line 31, in <module>
    session.create_advanced_sequence('my_sequence', attribute_ids)
  File "C:\Python27\lib\site-packages\nidcpower\session.py", line 4338, in create_advanced_sequence
    error_code = self._library.niDCPower_CreateAdvancedSequence(self._vi, sequence_name.encode(self._encoding), attribute_id_count, attribute_ids, set_as_active_sequence)
  File "C:\Python27\lib\site-packages\nidcpower\library.py", line 142, in niDCPower_CreateAdvancedSequence
    return self.niDCPower_CreateAdvancedSequence_cfunc(vi, sequence_name, attribute_id_count, attribute_ids, set_as_active_sequence)
ctypes.ArgumentError: argument 4: <type 'exceptions.TypeError'>: expected LP_c_long instance instead of list
```

**Comment by marcoskirsch** [comment]
I have a fix for this in branch https://github.com/ni/nimi-python/tree/explicit-ctypes-variables but it's nowhere ready for merging because the unit tests require a lot of retrofits.
